server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /positions/promtail-positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: observability_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: observability_logs
          __path__: /var/log/myapp/app.log


    pipeline_stages:
      - json:
          expressions:
            tenantId: tenantId
            userId: userId
            projectId: projectId
            action: action
            resource: resource
      - labels:
          tenantId:
          projectId:
          userId: