spring:
  application:
    name: observability

  datasource:
    url: jdbc:postgresql://localhost:5432/observability_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 0
      idle-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: agent_manager

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/observability
          jwk-set-uri: http://localhost:8080/realms/observability/protocol/openid-connect/certs

server:
  port: 4000
  servlet:
    context-path: /${spring.application.name}/api/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
  level:
    root: INFO

multitenancy:
  header-name: x-tenant-key
  default-tenant: master

jwt:
  auth:
    converter:
      resource-id: observability-backend-app
      principle-attribute: preferred_username