package com.aurora.observability.repository.implementation;

import com.aurora.observability.entity.Agent;
import com.aurora.observability.repository.AgentRepository;
import jakarta.persistence.EntityManager;
import jakarta.persistence.TypedQuery;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * Custom repository implementation for performing persistence operations on
 * {@link Agent} entities using the JPA {@link EntityManager}.
 * <p>
 * This implementation provides lower-level control over database interactions
 * compared to Spring Data JPA's autogenerated methods. It is especially useful
 * when more customized queries or fine-grained transaction handling is required.
 * </p>
 */
@RequiredArgsConstructor
@Repository
public class AgentRepositoryImpl implements AgentRepository {

    private final EntityManager entityManager;

    /**
     * Persists a new {@link Agent} entity into the database.
     * <p>
     * This method uses {@link EntityManager#persist(Object)} which schedules
     * the entity for insertion within the current persistence context.
     * </p>
     *
     * @param agentData the {@link Agent} entity to be saved (must not be {@code null})
     */
    @Override
    public void save(Agent agentData) {
        entityManager.persist(agentData);
    }

    /**
     * Retrieves an {@link Agent} entity by its unique identifier.
     *
     * @param id the UUID of the agent to retrieve (must not be {@code null})
     * @return an {@link Optional} containing the found entity, or empty if no agent exists with the given ID
     */
    @Override
    public Optional<Agent> findById(UUID id) {
        return Optional.ofNullable(entityManager.find(Agent.class, id));
    }

    /**
     * Retrieves all {@link Agent} entities from the database.
     * <p>
     * Executes a JPQL query equivalent to {@code SELECT a FROM Agent a}.
     * </p>
     *
     * @return a list of all stored {@link Agent} entities (never {@code null})
     */
    @Override
    public List<Agent> findAll() {
        TypedQuery<Agent> query = entityManager.createQuery("FROM Agent", Agent.class);
        return query.getResultList();
    }
}
